image: alpine:3.8
services:
  - postgres:10-alpine

variables:
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test

before_script:
  - apk add py3-psycopg2 py3-pytest
  - echo "psql = {'host': 'postgres', 'user': 'test', 'passwd': 'test', 'db': 'test'}" > sqlconfig.py

test:
  script:
    - pytest-3
