language: python
python:
  - "3.6"

sudo: required

services:
  - docker

install:
  - pip install psycopg2 pytest

before_script:
  - docker pull postgres:10-alpine
  - docker run --name postgres -p 127.0.0.1:5432:5432 -e POSTGRES_PASSWORD=test -e POSTGRES_USER=test -d postgres:10-alpine
  - docker ps -a

script:
  - pytest

